#!/bin/bash
set -euo pipefail

# Usage: bash prepare_pseudo_label0_2gpu_oomsafe.sh <dataset_name> <scale>
# Example: bash prepare_pseudo_label0_2gpu_oomsafe.sh 006 2
#
# Override the conservative defaults if needed, e.g.:
# SAM_POINTS_SIDE=24 SAM_POINTS_BATCH=4 SAM_MAX_SIDE=960 bash prepare_pseudo_label0_2gpu_oomsafe.sh 006 1

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <dataset_name> <scale>"
    exit 1
fi

dataset_name="$1"
scale="$2"
dataset_folder="data/${dataset_name}"

if [ ! -d "$dataset_folder" ]; then
    echo "Error: Folder '$dataset_folder' does not exist."
    exit 2
fi

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

# Conservative defaults for 24 GB GPUs and high-resolution COLMAP/3DGS images.
CHUNK_SIZE="${CHUNK_SIZE:-2}"
NUM_WORKERS="${NUM_WORKERS:-4}"
DETECTION_EVERY="${DETECTION_EVERY:-5}"
MAX_NUM_OBJECTS="${MAX_NUM_OBJECTS:-150}"
SAM_POINTS_SIDE="${SAM_POINTS_SIDE:-32}"
SAM_POINTS_BATCH="${SAM_POINTS_BATCH:-8}"
SAM_MAX_SIDE="${SAM_MAX_SIDE:-1280}"
SAM_IOU="${SAM_IOU:-0.88}"
SAM_OVERLAP="${SAM_OVERLAP:-0.8}"

cd Tracking-Anything-with-DEVA/

if [ "$scale" = "1" ]; then
    img_path="../data/${dataset_name}/images"
else
    img_path="../data/${dataset_name}/images_${scale}"
fi

if [ ! -d "$img_path" ]; then
    echo "Error: Image folder '$img_path' does not exist. Try another scale, e.g. 1, 2, 4, or 8."
    exit 3
fi

out_dir="./example/output_gaussian_dataset/${dataset_name}"
mkdir -p "$out_dir"
# Avoid accidentally using stale partial outputs from a previous OOM run.
rm -rf "${out_dir}/Annotations" "${out_dir}/Annotations_color" "${out_dir}/pred.json"

common_args=(
  --chunk_size "$CHUNK_SIZE"
  --img_path "$img_path"
  --amp
  --temporal_setting semionline
  --detection_every "$DETECTION_EVERY"
  --size 480
  --output "$out_dir"
  --suppress_small_objects
  --max_num_objects "$MAX_NUM_OBJECTS"
  --SAM_NUM_POINTS_PER_SIDE "$SAM_POINTS_SIDE"
  --SAM_NUM_POINTS_PER_BATCH "$SAM_POINTS_BATCH"
  --SAM_PRED_IOU_THRESHOLD "$SAM_IOU"
  --SAM_OVERLAP_THRESHOLD "$SAM_OVERLAP"
  --deva_device cuda:0
  --sam_device cuda:1
  --sam_max_side "$SAM_MAX_SIDE"
  --sam_oom_retries 3
  --sam_min_points_per_batch 1
  --empty_cache_every 1
  --num_workers "$NUM_WORKERS"
)

echo "Using CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
echo "img_path=${img_path}"
echo "SAM_POINTS_SIDE=${SAM_POINTS_SIDE}, SAM_POINTS_BATCH=${SAM_POINTS_BATCH}, SAM_MAX_SIDE=${SAM_MAX_SIDE}, SAM_IOU=${SAM_IOU}"

# colored mask for visualization check
python demo/demo_automatic0_2gpu_oomsafe.py "${common_args[@]}"

if [ -d "${out_dir}/Annotations" ]; then
    rm -rf "${out_dir}/Annotations_color"
    mv "${out_dir}/Annotations" "${out_dir}/Annotations_color"
else
    echo "Error: ${out_dir}/Annotations was not generated by the colored-mask run."
    exit 4
fi

# gray mask for training
rm -rf "${out_dir}/Annotations" "${out_dir}/pred.json"
python demo/demo_automatic0_2gpu_oomsafe.py "${common_args[@]}" --use_short_id

if [ -d "${out_dir}/Annotations" ]; then
    rm -rf "../data/${dataset_name}/object_mask"
    cp -r "${out_dir}/Annotations" "../data/${dataset_name}/object_mask"
else
    echo "Error: ${out_dir}/Annotations was not generated by the gray-mask run."
    exit 5
fi

cd ..
echo "Pseudo-label generation COMPLETE: data/${dataset_name}/object_mask"
