# leisaac/devices/rule_grasp_keyboard.py
import carb
import omni.kit.app

from .device_base import Device

class RuleGraspKeyboard(Device):
    """
    Minimal Kit keyboard listener for rule-grasp mode:
    - No action generation (advance() returns None)
    - Provides add_callback(key, fn) for one-shot key press events
    """

    def __init__(self, env):
        super().__init__(env, "rule-grasp-keyboard")

        self._callbacks = {}          # key(str)->callable
        self._kit_input = None
        self._kit_keyboard = None
        self._kit_sub = None

        self._install_listener()

    def __del__(self):
        self.close()

    def close(self):
        # Safe unsubscribe
        try:
            if self._kit_input is not None and self._kit_sub is not None:
                if self._kit_keyboard is not None:
                    # keyboard-events
                    for name in ["unsubscribe_to_keyboard_events", "unsubscribe_from_keyboard_events"]:
                        if hasattr(self._kit_input, name):
                            getattr(self._kit_input, name)(self._kit_keyboard, self._kit_sub)
                            break
                else:
                    # input-events
                    for name in ["unsubscribe_to_input_events", "unsubscribe_from_input_events"]:
                        if hasattr(self._kit_input, name):
                            getattr(self._kit_input, name)(self._kit_sub)
                            break
        except Exception:
            pass
        self._kit_sub = None
        self._kit_keyboard = None
        self._kit_input = None

    def add_callback(self, key: str, fn):
        # Normalize
        k = str(key).upper()
        self._callbacks[k] = fn

    def reset(self):
        # nothing to reset
        return

    def advance(self):
        # no actions generated by input device in rule-grasp mode
        return None

    # ------------------------
    # internals
    # ------------------------
    def _key_input_from_name(self, key_name: str):
        key_name = str(key_name).upper()
        mapping = {chr(ord("A")+i): getattr(carb.input.KeyboardInput, chr(ord("A")+i)) for i in range(26)}
        mapping["SPACE"] = carb.input.KeyboardInput.SPACE
        return mapping.get(key_name, None)

    def _dispatch(self, key_name: str):
        fn = self._callbacks.get(str(key_name).upper(), None)
        if fn is not None:
            try:
                fn()
            except Exception as e:
                print(f"[rule-grasp-keyboard] callback error for key={key_name}: {e}")

    def _install_listener(self):
        self._kit_input = carb.input.acquire_input_interface()

        app = omni.kit.app.get_app()
        kb = None
        for name in ["get_platform_keyboard", "get_keyboard", "get_default_keyboard"]:
            if hasattr(app, name):
                try:
                    kb = getattr(app, name)()
                    if kb is not None:
                        break
                except Exception:
                    kb = None

        if kb is None:
            # fallback on input interface
            for name in ["get_keyboard_device", "get_keyboard", "get_default_keyboard"]:
                if hasattr(self._kit_input, name):
                    try:
                        kb = getattr(self._kit_input, name)()
                        if kb is not None:
                            break
                    except Exception:
                        kb = None

        # preferred: keyboard events
        if kb is not None and hasattr(self._kit_input, "subscribe_to_keyboard_events"):
            self._kit_keyboard = kb

            def _on_keyboard_event(event, *args, **kwargs):
                # only press
                try:
                    if event.type != carb.input.KeyboardEventType.KEY_PRESS:
                        return
                except Exception:
                    pass

                # event.input is KeyboardInput; try match any registered key
                # We reverse-map KeyboardInput -> letter by comparing candidates
                # Fast path: handle A-Z + SPACE
                for k in list(self._callbacks.keys()):
                    inp = self._key_input_from_name(k)
                    if inp is not None and hasattr(event, "input") and event.input == inp:
                        self._dispatch(k)
                        break

            self._kit_sub = self._kit_input.subscribe_to_keyboard_events(self._kit_keyboard, _on_keyboard_event)
            print("[rule-grasp-keyboard] Kit key listener active (keyboard-events). Click viewport to focus.")
            return

        # fallback: input events
        if hasattr(self._kit_input, "subscribe_to_input_events"):
            def _on_input_event(event, *args, **kwargs):
                # filter keyboard press best-effort
                try:
                    if hasattr(event, "deviceType") and event.deviceType != carb.input.DeviceType.KEYBOARD:
                        return
                except Exception:
                    pass

                pressed = None
                try:
                    pressed = (event.type == carb.input.KeyboardEventType.KEY_PRESS)
                except Exception:
                    pass
                if pressed is None and hasattr(event, "value"):
                    try:
                        pressed = (float(event.value) > 0.5)
                    except Exception:
                        pressed = False
                if not pressed:
                    return

                for k in list(self._callbacks.keys()):
                    inp = self._key_input_from_name(k)
                    if inp is not None and hasattr(event, "input") and event.input == inp:
                        self._dispatch(k)
                        break

            self._kit_keyboard = None
            self._kit_sub = self._kit_input.subscribe_to_input_events(_on_input_event)
            print("[rule-grasp-keyboard] Kit key listener active (input-events). Click viewport to focus.")
            return

        print("[rule-grasp-keyboard] ERROR: no compatible subscription API found.")
